[system.link]
home = [
  [".zshrc", ".zshrc"],
  ["obsidian/snippets", "Documents/Obsidian Vault/.obsidian/snippets"]
]
[system.recursive]
root = [
	["firefox", "/usr/lib/firefox"],
	["thunderbird", "/usr/lib/thunderbird"],
	["chromium", "/etc/chromium"]
]

[install]
paru = [
  "zsh",
	"ttf-font-awesome",
	"noto-fonts",
	"noto-fonts-cjk",
	"flatpak",
	"xdg-desktop-portal",
	"xdg-desktop-portal-hyprland",
	"waybar",
	"syncthing",
	"ranger",
	"thunderbird",
	"npm",
	"btop",
	"wf-recorder",
	"gimp",
	"inotify-tools",
	"dart-sass",
	"swww",
	"ntfs-3g",
  "firefox",
  "wofi",
  "visual-studio-code-bin",
  "wev",
  "pfetch",
  "mpc",
  "teams",
  "grim",
  "slurp",
  "wl-clipboard",
  "pavucontrol",
  "dunst",
  "swayidle",
  "swaylock-effects",
  "sway-audio-idle-inhibit-git",
  "gradle",
  "kotlin",
  "qemu-base",
  "virt-manager",
  "libtpms",
  "edk2-ovmf",
  "bridge-utils",
  "cava",
  "firefoxpwa",
  "minecraft-launcher",
  "opera",
  "android-tools",
  "android-studio",
  "scrcpy",
  "vscodium-bin",
  "obsidian",
  "vivaldi",
  "zotero-bin",
  "mpd",
  "mpc",
  "mpd-discord-rpc",
  "waypipe"
]

flatpak = [
]

vsc = [
  "aaron-bond.better-comments",
  "tamasfe.even-better-toml",
  "catppuccin.catppuccin-vsc",
  "catppuccin.catppuccin-vsc-icons",
  "esbenp.prettier-vscode",
  "rust-lang.rust-analyzer",
  "ritwickdey.liveserver",
  "formulahendry.auto-close-tag",
  "html-validate.vscode-html-validate",
  "s-nlf-fh.glassit",
  "mathiasfrohlich.kotlin",
  "formulahendry.code-runner"
]
