$hyprC = ~/.config/hypr
source = $hyprC/startup.conf
source = $hyprC/workspaces.conf
source = $hyprC/env.conf
source = $hyprC/variables.conf
source = $hyprC/shortcuts.conf


windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.








