$mainMod = SUPER

bind = $mainMod, Return, exec, kitty
bind = $mainMod_SHIFT, Q, exit, 
bind = $mainMod, R, exec, wofi
# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, P, exec, ~/.config/hypr/disableMonitor
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
bind = $mainMod_SHIFT, X, exec, killall swhks
bind = $mainMod, C, killactive
bind = $mainMod, X, exec, swhks & pkexec swhkd --config ~/.config/swhkd/swhkdrc
bind = $mainMod, Space, togglefloating
bind = $mainMod, f, fullscreen
bind = $mainMod, S, togglespecialworkspace
bind = $mainMod, P, pin
bind = $mainMod, period, exec, flatpak run com.tomjwatson.Emote
#bind = ,XF86AudioRaiseVolume, exec, pactl set-sink-volume 0 +5%
bind = $mainMod_CTRL, Up, exec, pactl set-sink-volume 0 +5%
bind = $mainMod_CTRL, Down, exec, pactl set-sink-volume 0 -5%
bind = ,Print, exec, grim -g "$(slurp)" - | wl-copy
# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
