exec = swww-daemon && swww img ~/.config/hypr/wallpaperflare.com_wallpaper.jpg
exec-once = obsidian
exec = syncthing
exec-once = ~/.config/waybar/waybarStart
exec = sway-audio-idle-inhibit
exec = thunderbird
exec = snapchat
exec = discord
exec = dunst
