####                            ####
####    Monitor Configuration   ####
####                            ####

#Desktop
$m1=DP-2
$m2=HDMI-A-2
monitor=DP-2, 2560x1440@144, 0x0, 1
monitor=HDMI-A-2, 1920x1080, 2560x0, 1

#Laptop
#$m1=eDP-1
#$m2=HDMI-A-1
#monitor=eDP-1, 1920x1080, 0x0, 1
#monitor=HDMI-A-1, 1920x1080, 0x1080, 1

workspace=1,monitor:$m1
workspace=2,monitor:$m1
workspace=3,monitor:$m1
workspace=4,monitor:$m1
workspace=5,monitor:$m1
workspace=6,monitor:$m1
workspace=7,monitor:$m1
workspace=8,monitor:$m1
workspace=9,monitor:$m1

workspace=10,monitor:$m2
workspace=11,monitor:$m2
workspace=12,monitor:$m2
workspace=13,monitor:$m2
workspace=14,monitor:$m2
workspace=15,monitor:$m2
workspace=16,monitor:$m2
workspace=17,monitor:$m2
workspace=18,monitor:$m2

####                            ####
####    Workspace Navigation    ####
####                            ####
$mainMod = SUPER
$hypr=~/.config/hypr/scripts/toggleworkspace
bind = $mainMod, KP_End, exec, $hypr 1
bind = $mainMod, KP_Down, exec, $hypr 2
bind = $mainMod, KP_Next, exec, $hypr 3
bind = $mainMod, KP_Left, exec, $hypr 4
bind = $mainMod, KP_Begin, exec, $hypr 5
bind = $mainMod, KP_Right, exec, $hypr 6
bind = $mainMod, KP_Home, exec, $hypr 7
bind = $mainMod, KP_Up, exec, $hypr 8
bind = $mainMod, KP_Prior, exec, $hypr 9

bind = $mainMod_ALT, KP_End, exec, $hypr 10
bind = $mainMod_ALT, KP_Down, exec, $hypr 11
bind = $mainMod_ALT, KP_Next, exec, $hypr 12
bind = $mainMod_ALT, KP_Left, exec, $hypr 13
bind = $mainMod_ALT, KP_Begin, exec, $hypr 14
bind = $mainMod_ALT, KP_Right, exec, $hypr 15
bind = $mainMod_ALT, KP_Home, exec, $hypr 16
bind = $mainMod_ALT, KP_Up, exec, $hypr 17
bind = $mainMod_ALT, KP_Prior, exec, $hypr 18

bind = $mainMod_CTRL, KP_End, movetoworkspace, 1
bind = $mainMod_CTRL, KP_Down, movetoworkspace, 2
bind = $mainMod_CTRL, KP_Next, movetoworkspace, 3
bind = $mainMod_CTRL, KP_Left, movetoworkspace, 4
bind = $mainMod_CTRL, KP_Begin, movetoworkspace, 5
bind = $mainMod_CTRL, KP_Right, movetoworkspace, 6
bind = $mainMod_CTRL, KP_Home, movetoworkspace, 7
bind = $mainMod_CTRL, KP_Up, movetoworkspace, 8
bind = $mainMod_CTRL, KP_Prior, movetoworkspace, 9

bind = $mainMod_ALT SHIFT, KP_End, movetoworkspace, 10
bind = $mainMod ALT SHIFT, KP_Down, movetoworkspace, 11
bind = $mainMod_ALT SHIFT, KP_Next, movetoworkspace, 12
bind = $mainMod_ALT SHIFT, KP_Left, movetoworkspace, 13
bind = $mainMod_ALT SHIFT, KP_Begin, movetoworkspace, 14
bind = $mainMod_ALT SHIFT, KP_Right, movetoworkspace, 15
bind = $mainMod_ALT SHIFT, KP_Home, movetoworkspace, 16
bind = $mainMod_ALT SHIFT, KP_Up, movetoworkspace, 17
bind = $mainMod_ALT SHIFT, KP_Prior, movetoworkspace, 18

bind = $mainMod, T, exec, $hypr Thunderbird
bind = $mainMod, D, exec, $hypr Discord
bind = $mainMod, M, exec, $hypr Social
bind = $mainMod_CTRL, D,  movetoworkspace, name:Discord 
bind = $mainMod, G, workspace, name:Gaming
bind = $mainMod, O, togglespecialworkspace, obsidian

windowrule {
  name = picture
  match:initial_title = Picture-in-Picture
  float = on
  size = 274 182
  move = 2104 64
  pin = on
  }

windowrule {
    name = thunderbird
    match:class = org.mozilla.Thunderbird
    workspace = name:Thunderbird silent
  }

windowrule {
    name = Snapchat
    match:class = FFPWA-01KFBRQ7RSKE42P9CVDDS34H17
    workspace = name:Social silent
  }

windowrule {
    name = Obsidian
    match:class = obsidian
    workspace = special:obsidian silent
  }

windowrule {
    name = sxiv
    match:class = Sxiv
    fullscreen = on
  }

windowrule {
    name = Discord
    match:class = discord
    workspace = name:Social silent
  }
